---
- name: Ensure wheel is installed (Ubuntu 20.04).
  apt:
    name: python3-wheel
    state: present
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version == '20'

- name: Ensure pip is installed.
  apt:
    name: '{{ elasticsearch_curator_pip_package }}'
    state: present
